# Working with parquet files

## Objective

+ In this assignment, we will use the data downloaded with the module `data_manager` to create features.

(11 pts total)

## Prerequisites

+ This notebook assumes that price data is available to you in the environment variable `PRICE_DATA`. If you have not done so, then execute the notebook `01_materials/labs/2_data_engineering.ipynb` to create this data set.

+ Load the environment variables using dotenv. (1 pt)

In [1]:
# Write your code below.

%load_ext dotenv
%dotenv

In [2]:
import pandas as pd
import os
import sys
from glob import glob

sys.path.append(os.getenv('SRC_DIR'))

from utils.logger import get_logger
_logs = get_logger(__name__)

In [3]:
import dask.dataframe as dd

+ Load the environment variable `PRICE_DATA`.
+ Use [glob](https://docs.python.org/3/library/glob.html) to find the path of all parquet files in the directory `PRICE_DATA`.

(1pt)

In [4]:
# Load environment variables
PRICE_DATA = os.getenv('PRICE_DATA')


parquet_files = glob(os.path.join(PRICE_DATA, "**/*.parquet"), recursive = True)
dd_px = dd.read_parquet(parquet_files).set_index("ticker")

For each ticker and using Dask, do the following:

+ Add lags for variables Close and Adj_Close.
+ Add returns based on Close:
    
    - `returns`: (Close / Close_lag_1) - 1

+ Add the following range: 

    - `hi_lo_range`: this is the day's High minus Low.

+ Assign the result to `dd_feat`.

(4 pt)

In [ ]:
dd_shift = dd_px.groupby('ticker', group_keys=False).apply(
    lambda x: x.assign(Close_lag_1 = x['Close'].shift(1))
)

In [6]:
dd_rets = dd_shift.assign(
    Returns = lambda x: x['Close']/x['Close_lag_1'] - 1
)

In [7]:
dd_range = dd_shift.assign(
    Returns = lambda x: x['Close'] / x['Close_lag_1'] - 1,
    hi_lo_range = lambda x: x['High'] - x['Low']
)

In [8]:
dd_range

Dask DataFrame Structure:
                          Date     Open     High      Low    Close Adj Close   Volume  source   Year Close_lag_1  Returns hi_lo_range
npartitions=90
ACN             datetime64[ns]  float64  float64  float64  float64   float64  float64  string  int32     float64  float64     float64
AIHS                       ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...         ...
...                        ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...         ...
ZIXI                       ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...         ...
ZIXI                       ...      ...      ...      ...      ...       ...      ...     ...    ...         ...      ...         ...
Dask Name: assign, 14 expressions
Expr=Assign(frame=Assign(frame=Assign(frame=Assign(frame=GroupByApply(frame=SetIndex(frame=ReadParquetFSSpec(6a410b1), _other='ticker', options={}), observed=False, group_keys=False, func=<function <lambda> at 0x0000024310237BA0>, meta=<no_default>, args=(), kwargs={})))))

+ Convert the Dask data frame to a pandas data frame. 
+ Add a new feature containing the moving average of `returns` using a window of 10 days. There are several ways to solve this task, a simple one uses `.rolling(10).mean()`.

(3 pt)

In [9]:
df_feat = dd_range.compute()

In [10]:
df_feat['Returns_ma_10'] = (
    df_feat.groupby('ticker')['Returns']
    .transform(lambda x: x.rolling(10).mean())
)

In [11]:
df_feat.head(20)

,Date,Open,High,Low,Close,Adj Close,Volume,source,Year,Close_lag_1,Returns,hi_lo_range,Returns_ma_10
ticker,,,,,,,,,,,,,
ACN,2001-07-19,15.10,15.29,15.00,15.17,11.404394,34994300.0,ACN.csv,2001,NaN,NaN,0.290000,NaN
ACN,2001-07-20,15.05,15.05,14.80,15.01,11.284108,9238500.0,ACN.csv,2001,15.17,-0.010547,0.250000,NaN
ACN,2001-07-23,15.00,15.01,14.55,15.00,11.276587,7501000.0,ACN.csv,2001,15.01,-0.000666,0.460000,NaN
ACN,2001-07-24,14.95,14.97,14.70,14.86,11.171341,3537300.0,ACN.csv,2001,15.00,-0.009333,0.270000,NaN
ACN,2001-07-25,14.70,14.95,14.65,14.95,11.238999,4208100.0,ACN.csv,2001,14.86,0.006057,0.300000,NaN
ACN,2001-07-26,14.95,14.99,14.50,14.50,10.900705,6335300.0,ACN.csv,2001,14.95,-0.030100,0.490000,NaN
ACN,2001-07-27,14.51,14.59,14.50,14.51,10.908223,3524000.0,ACN.csv,2001,14.50,0.000690,0.090000,NaN
ACN,2001-07-30,14.50,14.78,14.50,14.70,11.051059,3654300.0,ACN.csv,2001,14.51,0.013094,0.280000,NaN
ACN,2001-07-31,14.71,15.01,14.60,14.96,11.246520,1429000.0,ACN.csv,2001,14.70,0.017687,0.410000,NaN
ACN,2001-08-01,15.00,15.50,14.90,15.50,11.652478,2087900.0,ACN.csv,2001,14.96,0.036096,0.600000,NaN
ACN,2001-08-02,15.40,15.50,15.10,15.40,11.577302,1717400.0,ACN.csv,2001,15.50,-0.006452,0.400000,0.001653
ACN,2001-08-03,15.40,15.40,14.98,15.15,11.389356,983600.0,ACN.csv,2001,15.40,-0.016234,0.420000,0.001084
ACN,2001-08-06,15.15,15.22,15.02,15.10,11.351768,777400.0,ACN.csv,2001,15.15,-0.003300,0.200000,0.000820
ACN,2001-08-07,15.10,15.55,15.10,15.50,11.652478,788900.0,ACN.csv,2001,15.10,0.026490,0.450000,0.004403
ACN,2001-08-08,15.40,15.60,15.00,15.00,11.276587,2190300.0,ACN.csv,2001,15.50,-0.032258,0.600000,0.000571
ACN,2001-08-09,15.05,15.50,15.00,15.50,11.652478,928000.0,ACN.csv,2001,15.00,0.033333,0.500000,0.006915
ACN,2001-08-10,15.40,15.40,15.12,15.19,11.419426,703300.0,ACN.csv,2001,15.50,-0.020000,0.280000,0.004846
ACN,2001-08-13,15.15,15.34,14.90,15.01,11.284108,1770400.0,ACN.csv,2001,15.19,-0.011850,0.440001,0.002351
ACN,2001-08-14,15.05,15.06,14.65,14.70,11.051059,1000800.0,ACN.csv,2001,15.01,-0.020653,0.410001,-0.001483
ACN,2001-08-15,14.75,14.90,14.70,14.79,11.118717,530900.0,ACN.csv,2001,14.70,0.006122,0.200000,-0.004480

Please comment:

+ Was it necessary to convert to pandas to calculate the moving average return?

No, it wasn’t strictly necessary to convert to pandas to calculate the moving average return. Dask can perform rolling window calculations too, but it’s more complex because Dask processes data in chunks (partitions) and needs extra steps to handle rolling calculations across those partitions correctly. Using pandas is simpler for rolling calculations, especially when the dataset fits into memory. So converting to pandas is often a practical shortcut for ease and correctness.


+ Would it have been better to do it in Dask? Why?

Doing the moving average calculation in Dask would be better for very large datasets that don’t fit into memory because Dask handles data in parallel and can scale across multiple cores or machines. However, it requires more careful setup to manage rolling windows across partitions. For smaller datasets, pandas is simpler and faster to use. So, Dask is better for big data, while pandas is easier for smaller or medium-sized data.

(1 pt)

## Criteria

The [rubric](./assignment_1_rubric_clean.xlsx) contains the criteria for grading.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `HH:MM AM/PM - DD/MM/YYYY`
* The branch name for your repo should be: `assignment-1`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_1.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/production/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#cohort-3-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.